In [46]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.metrics import classification_report

In [3]:
datos = pd.read_csv('C:/Users/brian/Downloads/archive (2)/survey lung cancer.csv')

# Bases de datos

In [4]:
datos

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0        M   69        1               2        2              1   
1        M   74        2               1        1              1   
2        F   59        1               1        1              2   
3        M   63        2               2        2              1   
4        F   63        1               2        1              1   
..     ...  ...      ...             ...      ...            ...   
304      F   56        1               1        1              2   
305      M   70        2               1        1              1   
306      M   58        2               1        1              1   
307      M   67        2               1        2              1   
308      M   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2   
1                  2         2         2         1                  1   
2                  1         2         1         2                  1   
3                  1         1         1         1                  2   
4                  1         1         1         2                  1   
..               ...       ...       ...       ...                ...   
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
0           2                    2                      2           2   
1           1                    2                      2           2   
2           2                    2                      1           2   
3           1                    1                      2           2   
4           2                    2                      1           1   
..        ...                  ...                    ...         ...   
304         2                    2                      2           1   
305         2                    2                      1           2   
306         2                    1                      1           2   
307         2                    2                      1           2   
308         1                    1                      2           1   

    LUNG_CANCER  
0           YES  
1           YES  
2            NO  
3            NO  
4            NO  
..          ...  
304         YES  
305         YES  
306         YES  
307         YES  
308         YES  

[309 rows x 16 columns]

In [5]:
datos.dtypes

GENDER                   object
AGE                       int64
SMOKING                   int64
YELLOW_FINGERS            int64
ANXIETY                   int64
PEER_PRESSURE             int64
CHRONIC DISEASE           int64
FATIGUE                   int64
ALLERGY                   int64
WHEEZING                  int64
ALCOHOL CONSUMING         int64
COUGHING                  int64
SHORTNESS OF BREATH       int64
SWALLOWING DIFFICULTY     int64
CHEST PAIN                int64
LUNG_CANCER              object
dtype: object

In [6]:
datos.dtypes=='object'

GENDER                    True
AGE                      False
SMOKING                  False
YELLOW_FINGERS           False
ANXIETY                  False
PEER_PRESSURE            False
CHRONIC DISEASE          False
FATIGUE                  False
ALLERGY                  False
WHEEZING                 False
ALCOHOL CONSUMING        False
COUGHING                 False
SHORTNESS OF BREATH      False
SWALLOWING DIFFICULTY    False
CHEST PAIN               False
LUNG_CANCER               True
dtype: bool

In [19]:
encoder = OrdinalEncoder()
datos[['GENDER', 'LUNG_CANCER']] = encoder.fit_transform(datos[['GENDER', 'LUNG_CANCER']])

In [20]:
datos

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0       1.0   69        1               2        2              1   
1       1.0   74        2               1        1              1   
2       0.0   59        1               1        1              2   
3       1.0   63        2               2        2              1   
4       0.0   63        1               2        1              1   
..      ...  ...      ...             ...      ...            ...   
304     0.0   56        1               1        1              2   
305     1.0   70        2               1        1              1   
306     1.0   58        2               1        1              1   
307     1.0   67        2               1        2              1   
308     1.0   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2   
1                  2         2         2         1                  1   
2                  1         2         1         2                  1   
3                  1         1         1         1                  2   
4                  1         1         1         2                  1   
..               ...       ...       ...       ...                ...   
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
0           2                    2                      2           2   
1           1                    2                      2           2   
2           2                    2                      1           2   
3           1                    1                      2           2   
4           2                    2                      1           1   
..        ...                  ...                    ...         ...   
304         2                    2                      2           1   
305         2                    2                      1           2   
306         2                    1                      1           2   
307         2                    2                      1           2   
308         1                    1                      2           1   

     LUNG_CANCER  
0            1.0  
1            1.0  
2            0.0  
3            0.0  
4            0.0  
..           ...  
304          1.0  
305          1.0  
306          1.0  
307          1.0  
308          1.0  

[309 rows x 16 columns]

In [26]:
X = datos.values[:,:-1]

In [27]:
X

array([[ 1., 69.,  1., ...,  2.,  2.,  2.],
       [ 1., 74.,  2., ...,  2.,  2.,  2.],
       [ 0., 59.,  1., ...,  2.,  1.,  2.],
       ...,
       [ 1., 58.,  2., ...,  1.,  1.,  2.],
       [ 1., 67.,  2., ...,  2.,  1.,  2.],
       [ 1., 62.,  1., ...,  1.,  2.,  1.]])

In [28]:
X = datos.values[:,0:15]

In [29]:
X

array([[ 1., 69.,  1., ...,  2.,  2.,  2.],
       [ 1., 74.,  2., ...,  2.,  2.,  2.],
       [ 0., 59.,  1., ...,  2.,  1.,  2.],
       ...,
       [ 1., 58.,  2., ...,  1.,  1.,  2.],
       [ 1., 67.,  2., ...,  2.,  1.,  2.],
       [ 1., 62.,  1., ...,  1.,  2.,  1.]])

In [30]:
X = datos.iloc[:,:-1]

In [32]:
X

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0       1.0   69        1               2        2              1   
1       1.0   74        2               1        1              1   
2       0.0   59        1               1        1              2   
3       1.0   63        2               2        2              1   
4       0.0   63        1               2        1              1   
..      ...  ...      ...             ...      ...            ...   
304     0.0   56        1               1        1              2   
305     1.0   70        2               1        1              1   
306     1.0   58        2               1        1              1   
307     1.0   67        2               1        2              1   
308     1.0   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2   
1                  2         2         2         1                  1   
2                  1         2         1         2                  1   
3                  1         1         1         1                  2   
4                  1         1         1         2                  1   
..               ...       ...       ...       ...                ...   
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  
0           2                    2                      2           2  
1           1                    2                      2           2  
2           2                    2                      1           2  
3           1                    1                      2           2  
4           2                    2                      1           1  
..        ...                  ...                    ...         ...  
304         2                    2                      2           1  
305         2                    2                      1           2  
306         2                    1                      1           2  
307         2                    2                      1           2  
308         1                    1                      2           1  

[309 rows x 15 columns]

In [33]:
y = datos.values[:,-1:]

In [34]:
y

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [36]:
print('el tamaño de X es: {}'.format(X.shape))
print('el tamaño de y es: {}'.format(y.shape))

el tamaño de X es: (309, 15)
el tamaño de y es: (309, 1)


In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [40]:
print('el tamaño de X_train es: {}'.format(X_train.shape))
print('el tamaño de X_test es: {}'.format(X_test.shape))
print('el tamaño de y_train es: {}'.format(y_train.shape))
print('el tamaño de y_test es: {}'.format(y_test.shape))

el tamaño de X_train es: (216, 15)
el tamaño de X_test es: (93, 15)
el tamaño de y_train es: (216, 1)
el tamaño de y_test es: (93, 1)


In [44]:
model = KNeighborsClassifier()
model.fit(X_train, y_train)
y_predicha = model.predict(X_test).reshape((93,1))

C:\Users\brian\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\brian\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [45]:
y_predicha.shape

(93, 1)

In [47]:
print(classification_report(y_test, y_predicha))

              precision    recall  f1-score   support

         0.0       0.40      0.57      0.47         7
         1.0       0.96      0.93      0.95        86

    accuracy                           0.90        93
   macro avg       0.68      0.75      0.71        93
weighted avg       0.92      0.90      0.91        93



In [48]:
modelo1 = DecisionTreeClassifier(max_depth=5)
cv = cross_val_score(modelo1, X_train, y_train, scoring = 'accuracy')
print(f'El accuracy es {cv.mean()*100}')

El accuracy es 85.68710359408034
